/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Project;
import javax.swing.JOptionPane;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.Locale;
import javax.swing.JInternalFrame;
import javax.swing.Timer;

/**
 *
 * @author LENOVO
 */
public class FORM_menuUtama extends javax.swing.JFrame {

    public void Tampil_Jam(){
    ActionListener taskPerformer = new ActionListener() {
        @Override
        public void actionPerformed(ActionEvent evt) {
            String nol_jam = "", nol_menit = "", nol_detik = "";
            java.util.Date dateTime = new java.util.Date();
            int nilai_jam = dateTime.getHours();
            int nilai_menit = dateTime.getMinutes();
            int nilai_detik = dateTime.getSeconds();
            if(nilai_jam <= 9) nol_jam = "0";
            if(nilai_menit <= 9) nol_menit = "0";
            if(nilai_detik <= 9) nol_detik = "0";
            String jam = nol_jam + Integer.toString(nilai_jam);
            String menit = nol_menit + Integer.toString(nilai_menit);
            String detik = nol_detik + Integer.toString(nilai_detik);
            Label_jam.setText(jam+":"+menit+":"+detik+"");
        }
    };
    new Timer(1000, taskPerformer).start();
}
    
    public void Tampil_Tanggal(){
    java.util.Date tglsekarang = new java.util.Date();
    SimpleDateFormat smpdtfmt = new SimpleDateFormat("dd MMMM yyyy",
            Locale.getDefault());
    String tanggal = smpdtfmt.format(tglsekarang);
    Label_tanggal.setText(tanggal);
}
    
    
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FORM_menuUtama.class.getName());

    /**
     * Creates new form FORM_menuUtama
     */
    public FORM_menuUtama() {
        initComponents();
        setTitle("Aplikasi Minimasrket");
        Tampil_Jam();
        Tampil_Tanggal();
        this.setExtendedState(FORM_menuUtama.MAXIMIZED_BOTH);
        btnuser.setEnabled(false);
        btnbuku.setEnabled(false);
        btnpenjualan.setEnabled(false);
        btntransaksi.setEnabled(false);
        btnlaporan.setEnabled(false);
        JMaster.setEnabled(false);
        JPenjualan.setEnabled(false);
        JLaporan.setEnabled(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnuser = new javax.swing.JButton();
        btnbuku = new javax.swing.JButton();
        btnpenjualan = new javax.swing.JButton();
        btntransaksi = new javax.swing.JButton();
        btnlaporan = new javax.swing.JButton();
        btnkeluar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        Label_tanggal = new javax.swing.JLabel();
        Label_jam = new javax.swing.JLabel();
        jDesktop = new javax.swing.JDesktopPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        JMaster = new javax.swing.JMenu();
        MUser = new javax.swing.JMenuItem();
        MBuku = new javax.swing.JMenuItem();
        MPenjualan = new javax.swing.JMenuItem();
        JPenjualan = new javax.swing.JMenu();
        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        JLaporan = new javax.swing.JMenu();
        JLaporanuser = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Aplikasi");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(153, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/icons8-supermarket-100 (1).png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 0, -1, 88));

        jLabel2.setText("Menu Utama");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, -1, -1));

        btnuser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/user.png"))); // NOI18N
        btnuser.setText("Data user");
        btnuser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnuserActionPerformed(evt);
            }
        });
        jPanel1.add(btnuser, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 128, 177, 70));

        btnbuku.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/004-shopping-basket.png"))); // NOI18N
        btnbuku.setText("Data Buku");
        btnbuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbukuActionPerformed(evt);
            }
        });
        jPanel1.add(btnbuku, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 210, 177, 70));

        btnpenjualan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/005-cashier-1.png"))); // NOI18N
        btnpenjualan.setText("Data Penjualan");
        btnpenjualan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpenjualanActionPerformed(evt);
            }
        });
        jPanel1.add(btnpenjualan, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 130, -1, 70));

        btntransaksi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/001-point-of-service.png"))); // NOI18N
        btntransaksi.setText("Transaksi Kasir");
        btntransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntransaksiActionPerformed(evt);
            }
        });
        jPanel1.add(btntransaksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 210, 177, 70));

        btnlaporan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/003-newspaper.png"))); // NOI18N
        btnlaporan.setText("Laporan");
        btnlaporan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlaporanActionPerformed(evt);
            }
        });
        jPanel1.add(btnlaporan, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 170, 70));

        btnkeluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/Actions-window-close-icon 24x24.png"))); // NOI18N
        btnkeluar.setText("Keluar");
        btnkeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnkeluarActionPerformed(evt);
            }
        });
        jPanel1.add(btnkeluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 300, 177, 70));

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Semangat kerja nya");
        jLabel3.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jLabel3AncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, -1, -1));
        jPanel1.add(namauser, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 30, 78, -1));

        Label_tanggal.setText("Tanggal :");
        Label_tanggal.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                Label_tanggalAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jPanel1.add(Label_tanggal, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 380, -1, -1));

        Label_jam.setText("Jam :");
        jPanel1.add(Label_jam, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 400, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 980));

        javax.swing.GroupLayout jDesktopLayout = new javax.swing.GroupLayout(jDesktop);
        jDesktop.setLayout(jDesktopLayout);
        jDesktopLayout.setHorizontalGroup(
            jDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 970, Short.MAX_VALUE)
        );
        jDesktopLayout.setVerticalGroup(
            jDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 910, Short.MAX_VALUE)
        );

        getContentPane().add(jDesktop, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 70, 970, 910));

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));

        jLabel20.setBackground(new java.awt.Color(255, 255, 255));
        jLabel20.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("AVARTUBOOK");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(354, 354, 354)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel20)
                .addContainerGap(433, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel5))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel20)))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 0, 1050, -1));

        JMaster.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/chart-search-icon 24x24.png"))); // NOI18N
        JMaster.setText("Master");

        MUser.setText("Data User");
        MUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MUserActionPerformed(evt);
            }
        });
        JMaster.add(MUser);

        MBuku.setText("Data Buku");
        MBuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MBukuActionPerformed(evt);
            }
        });
        JMaster.add(MBuku);

        MPenjualan.setText("Data Penjual");
        MPenjualan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MPenjualanActionPerformed(evt);
            }
        });
        JMaster.add(MPenjualan);

        jMenuBar1.add(JMaster);

        JPenjualan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/Distributor-report-icon 24x24.png"))); // NOI18N
        JPenjualan.setText("Penjualan");

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("Transaksi Kasir");
        jRadioButtonMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMenuItem1ActionPerformed(evt);
            }
        });
        JPenjualan.add(jRadioButtonMenuItem1);

        jMenuBar1.add(JPenjualan);

        JLaporan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/Text-Edit-icon 24x24.png"))); // NOI18N
        JLaporan.setText("Laporan");
        JLaporan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JLaporanActionPerformed(evt);
            }
        });

        JLaporanuser.setText("Laporan Perpriode");
        JLaporanuser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JLaporanuserActionPerformed(evt);
            }
        });
        JLaporan.add(JLaporanuser);

        jMenuItem3.setText("Laporan User");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        JLaporan.add(jMenuItem3);

        jMenuItem4.setText("Laporan Buku");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        JLaporan.add(jMenuItem4);
        JLaporan.add(jSeparator1);
        JLaporan.add(jSeparator2);

        jMenuBar1.add(JLaporan);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MUserActionPerformed
        // TODO add your handling code here:
    Form_User a = new Form_User();
    JInternalFrame internalFrame = new JInternalFrame("User",false,true,true);
    internalFrame.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    internalFrame.setContentPane(a.getContentPane());
    internalFrame.pack();
    a.setLocationRelativeTo(this);
    internalFrame.setVisible(true);
    jDesktop.add(internalFrame);
    }//GEN-LAST:event_MUserActionPerformed

    private void MPenjualanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MPenjualanActionPerformed
        // TODO add your handling code here:
            Form_DataTransaksi a = new Form_DataTransaksi();
    JInternalFrame internalFrame = new JInternalFrame("DATA PENJUALAN",false,true,true);
    internalFrame.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    internalFrame.setContentPane(a.getContentPane());
    internalFrame.pack();
    a.setLocationRelativeTo(this);
    internalFrame.setVisible(true);
    jDesktop.add(internalFrame);
    }//GEN-LAST:event_MPenjualanActionPerformed

    private void JLaporanuserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JLaporanuserActionPerformed
        // TODO add your handling code here:
    FORM_cetakPERPRIODE a = new FORM_cetakPERPRIODE();
    JInternalFrame internalFrame = new JInternalFrame("Laporanperpriode",false,true,true);
    internalFrame.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    internalFrame.setContentPane(a.getContentPane());
    internalFrame.pack();
    a.setLocationRelativeTo(this);
    internalFrame.setVisible(true);
    jDesktop.add(internalFrame);
    }//GEN-LAST:event_JLaporanuserActionPerformed

    private void jRadioButtonMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMenuItem1ActionPerformed
        // TODO add your handling code here:
    Form_Transaksi a = new Form_Transaksi();
    JInternalFrame internalFrame = new JInternalFrame("Transaksi",false,true,true);
    internalFrame.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    internalFrame.setContentPane(a.getContentPane());
    internalFrame.pack();
    a.setLocationRelativeTo(this);
    internalFrame.setVisible(true);
    jDesktop.add(internalFrame);
    }//GEN-LAST:event_jRadioButtonMenuItem1ActionPerformed

    private void btnuserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnuserActionPerformed
    // TODO add your handling code here:
    Form_User a = new Form_User();
    JInternalFrame internalFrame = new JInternalFrame("User",false,true,true);
    internalFrame.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    internalFrame.setContentPane(a.getContentPane());
    internalFrame.pack();
    a.setLocationRelativeTo(this);
    internalFrame.setVisible(true);
    jDesktop.add(internalFrame);
    }//GEN-LAST:event_btnuserActionPerformed

    private void btnpenjualanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpenjualanActionPerformed
        // TODO add your handling code here:
    Form_DataTransaksi a = new Form_DataTransaksi();
    JInternalFrame internalFrame = new JInternalFrame("DATA PENJUALAN",false,true,true);
    internalFrame.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    internalFrame.setContentPane(a.getContentPane());
    internalFrame.pack();
    a.setLocationRelativeTo(this);
    internalFrame.setVisible(true);
    jDesktop.add(internalFrame);
    }//GEN-LAST:event_btnpenjualanActionPerformed

    private void btnlaporanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlaporanActionPerformed
        // TODO add your handling code here:
    FORM_laporanBUKU_USER a = new FORM_laporanBUKU_USER();
    JInternalFrame internalFrame = new JInternalFrame("Laporan",false,true,true);
    internalFrame.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    internalFrame.setContentPane(a.getContentPane());
    internalFrame.pack();
    a.setLocationRelativeTo(this);
    internalFrame.setVisible(true);
    jDesktop.add(internalFrame);
    }//GEN-LAST:event_btnlaporanActionPerformed

    private void btntransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntransaksiActionPerformed
        // TODO add your handling code here:
    Form_Transaksi a = new Form_Transaksi();
    JInternalFrame internalFrame = new JInternalFrame("Transaksi",false,true,true);
    internalFrame.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    internalFrame.setContentPane(a.getContentPane());
    internalFrame.pack();
    a.setLocationRelativeTo(this);
    internalFrame.setVisible(true);
    jDesktop.add(internalFrame);
    }//GEN-LAST:event_btntransaksiActionPerformed

    private void btnkeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnkeluarActionPerformed
        // TODO add your handling code here:
            int pilihan = JOptionPane.showConfirmDialog(null,
            "Apakah anda ingin keluar dari program ?",
            "Title Keluar:", JOptionPane.YES_NO_OPTION);
        if (pilihan==JOptionPane.YES_OPTION)
        this.dispose();
        else
            btnuser.requestFocus();
    }//GEN-LAST:event_btnkeluarActionPerformed

    private void btnbukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbukuActionPerformed
        // TODO add your handling code here:
        Form_Buku a = new Form_Buku();
    JInternalFrame internalFrame = new JInternalFrame("Buku",false,true,true);
    internalFrame.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    internalFrame.setContentPane(a.getContentPane());
    internalFrame.pack();
    a.setLocationRelativeTo(this);
    internalFrame.setVisible(true);
    jDesktop.add(internalFrame);
    }//GEN-LAST:event_btnbukuActionPerformed

    private void MBukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MBukuActionPerformed
        // TODO add your handling code here:
                Form_Buku a = new Form_Buku();
    JInternalFrame internalFrame = new JInternalFrame("Buku",false,true,true);
    internalFrame.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    internalFrame.setContentPane(a.getContentPane());
    internalFrame.pack();
    a.setLocationRelativeTo(this);
    internalFrame.setVisible(true);
    jDesktop.add(internalFrame);
    }//GEN-LAST:event_MBukuActionPerformed

    private void JLaporanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JLaporanActionPerformed
        // TODO add your handling code here:
     FORM_cetakPERPRIODE a = new FORM_cetakPERPRIODE();
    JInternalFrame internalFrame = new JInternalFrame("Transaksi",false,true,true);
    internalFrame.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    internalFrame.setContentPane(a.getContentPane());
    internalFrame.pack();
    a.setLocationRelativeTo(this);
    internalFrame.setVisible(true);
    jDesktop.add(internalFrame);
    }//GEN-LAST:event_JLaporanActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
    FORM_laporanBUKU_USER a = new FORM_laporanBUKU_USER();
    JInternalFrame internalFrame = new JInternalFrame("LAPORAN BUKU",false,true,true);
    internalFrame.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    internalFrame.setContentPane(a.getContentPane());
    internalFrame.pack();
    a.setLocationRelativeTo(this);
    internalFrame.setVisible(true);
    jDesktop.add(internalFrame);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
      FORM_laporanBUKU_USER a = new FORM_laporanBUKU_USER();
    JInternalFrame internalFrame = new JInternalFrame("LAPORAN USER",false,true,true);
    internalFrame.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    internalFrame.setContentPane(a.getContentPane());
    internalFrame.pack();
    a.setLocationRelativeTo(this);
    internalFrame.setVisible(true);
    jDesktop.add(internalFrame);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jLabel3AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jLabel3AncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel3AncestorAdded

    private void Label_tanggalAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_Label_tanggalAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_Label_tanggalAncestorAdded

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FORM_menuUtama().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JMenu JLaporan;
    private javax.swing.JMenuItem JLaporanuser;
    public javax.swing.JMenu JMaster;
    public javax.swing.JMenu JPenjualan;
    private javax.swing.JLabel Label_jam;
    private javax.swing.JLabel Label_tanggal;
    public javax.swing.JMenuItem MBuku;
    public javax.swing.JMenuItem MPenjualan;
    public javax.swing.JMenuItem MUser;
    public javax.swing.JButton btnbuku;
    public javax.swing.JButton btnkeluar;
    public javax.swing.JButton btnlaporan;
    public javax.swing.JButton btnpenjualan;
    public javax.swing.JButton btntransaksi;
    public javax.swing.JButton btnuser;
    private javax.swing.JDesktopPane jDesktop;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    public static final javax.swing.JLabel namauser = new javax.swing.JLabel();
    // End of variables declaration//GEN-END:variables
}
