/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Project;
import Koneksi.Koneksi;
import java.sql.Connection;
import java.sql.Statement;
import java.sql.ResultSet;


import java.io.File;
import java.sql.SQLException;
import java.util.HashMap;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;
/**
/**
 *
 * @author LENOVO
 */
public class FORM_laporanBUKU_USER extends javax.swing.JFrame {
    private void listComboBox(){
        try{
            String sql="SELECT * FROM user";
            java.sql.Connection conn = (Connection)Koneksi.configDB();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet res = stm.executeQuery(sql);
            while (res.next()){
                cbuser.addItem(res.getNString("username"));
            }
        
        }catch(SQLException e) {
        System.out.println("Error :" + e.getMessage());
        }
    }
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FORM_laporanBUKU_USER.class.getName());
    
    /**
     * Creates new form FORM_laaporanBUKU_USER
     */
    public FORM_laporanBUKU_USER() {
        initComponents();
        listComboBox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tgl = new com.toedter.calendar.JDateChooser();
        cbuser = new javax.swing.JComboBox<>();
        ctkuser = new javax.swing.JButton();
        ctkbuku = new javax.swing.JButton();
        ctkperhariuser = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(153, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Tanggal");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, -1, -1));

        jLabel2.setText("Nama User");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, -1, -1));
        jPanel2.add(tgl, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 40, -1, -1));

        cbuser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbuserActionPerformed(evt);
            }
        });
        cbuser.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cbuserKeyReleased(evt);
            }
        });
        jPanel2.add(cbuser, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, 85, -1));

        ctkuser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/Printer-icon.png"))); // NOI18N
        ctkuser.setText("Cetak User");
        ctkuser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ctkuserActionPerformed(evt);
            }
        });
        jPanel2.add(ctkuser, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 70, -1, -1));

        ctkbuku.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/Printer-icon.png"))); // NOI18N
        ctkbuku.setText("Cetak Buku");
        ctkbuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ctkbukuActionPerformed(evt);
            }
        });
        jPanel2.add(ctkbuku, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 30, -1, -1));

        ctkperhariuser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/Printer-icon.png"))); // NOI18N
        ctkperhariuser.setText("Cetak Perhari & User");
        ctkperhariuser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ctkperhariuserActionPerformed(evt);
            }
        });
        jPanel2.add(ctkperhariuser, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, 290, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, 470, 210));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/003-newspaper.png"))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Cetak Laporan ");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, 72));

        jLabel20.setBackground(new java.awt.Color(0, 0, 0));
        jLabel20.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel20.setText("AVARTUBOOK");
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 673, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbuserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbuserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbuserActionPerformed

    private void cbuserKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cbuserKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_cbuserKeyReleased

    private void ctkuserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ctkuserActionPerformed
        // TODO add your handling code here:
    JasperReport jr;
    JasperPrint jp;
    JasperDesign jd;
    try {
        //Map <String, Object> parameter = new HashMap <String, Object>();
        java.sql.Connection conn = (Connection) Koneksi.configDB();
        HashMap parameter = new HashMap();
        //parameter.put("user",user,);
        //sesuaikan folder dan nama ireportnya
        File report = new File("src/Laporan/tabeluser.jrxml");
        jd = JRXmlLoader.load(report);
        jr = JasperCompileManager.compileReport(jd);
        jp = JasperFillManager.fillReport(jr, parameter, conn);
        JasperViewer.viewReport(jp, false);
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, e.getMessage());
    }
    }//GEN-LAST:event_ctkuserActionPerformed

    private void ctkperhariuserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ctkperhariuserActionPerformed
        // TODO add your handling code here:
        JasperReport jr;
    JasperPrint jp;
    JasperDesign jd;
    try {
        //Map <String, Object> parameter = new HashMap <String, Object>();
        java.sql.Connection conn = (Connection) Koneksi.configDB();
        HashMap parameter = new HashMap();
        parameter.put("hari", tgl.getDate());
        parameter.put("user", cbuser.getSelectedItem());
        //sesuaikan folder dan nama ireportnya
        File report = new File("src/Laporan/penjualanharian_user.jrxml");
        jd = JRXmlLoader.load(report);
        jr = JasperCompileManager.compileReport(jd);
        jp = JasperFillManager.fillReport(jr, parameter, conn);
        JasperViewer.viewReport(jp, false);
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, e.getMessage());
    }
    }//GEN-LAST:event_ctkperhariuserActionPerformed

    private void ctkbukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ctkbukuActionPerformed
        // TODO add your handling code here:
            JasperReport jr;
    JasperPrint jp;
    JasperDesign jd;
    try {
        //Map <String, Object> parameter = new HashMap <String, Object>();
        java.sql.Connection conn = (Connection) Koneksi.configDB();
        HashMap parameter = new HashMap();
        //parameter.put("user",user,);
        //sesuaikan folder dan nama ireportnya
        File report = new File("src/Laporan/tabelbuku.jrxml");
        jd = JRXmlLoader.load(report);
        jr = JasperCompileManager.compileReport(jd);
        jp = JasperFillManager.fillReport(jr, parameter, conn);
        JasperViewer.viewReport(jp, false);
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, e.getMessage());
    }
    }//GEN-LAST:event_ctkbukuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FORM_laporanBUKU_USER().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbuser;
    private javax.swing.JButton ctkbuku;
    private javax.swing.JButton ctkperhariuser;
    private javax.swing.JButton ctkuser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private com.toedter.calendar.JDateChooser tgl;
    // End of variables declaration//GEN-END:variables
}
