/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Project;
import Koneksi.Koneksi;
import java.io.File;
import java.sql.Connection;
import java.util.HashMap;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;
/**
 *
 * @author LENOVO
 */
public class FORM_cetakPERPRIODE extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FORM_cetakPERPRIODE.class.getName());

    /**
     * Creates new form FORM_cetakPERPRIODE
     */
    public FORM_cetakPERPRIODE() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        tanggal3 = new com.toedter.calendar.JDateChooser();
        tgltahun = new com.toedter.calendar.JDateChooser();
        tglhari = new com.toedter.calendar.JDateChooser();
        ctkperhari = new javax.swing.JButton();
        tanggal2 = new com.toedter.calendar.JDateChooser();
        ctkperbulan = new javax.swing.JButton();
        ctkpertahun = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0));
        filler2 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jPanel2.setBackground(new java.awt.Color(153, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.add(tanggal3, new org.netbeans.lib.awtextra.AbsoluteConstraints(146, 188, 145, -1));
        jPanel2.add(tgltahun, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 110, 100, 30));
        jPanel2.add(tglhari, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, 140, 30));

        ctkperhari.setBackground(new java.awt.Color(102, 102, 102));
        ctkperhari.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/Printer-icon.png"))); // NOI18N
        ctkperhari.setText("Cetak Perhari");
        ctkperhari.setAlignmentY(0.8F);
        ctkperhari.setIconTextGap(5);
        ctkperhari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ctkperhariActionPerformed(evt);
            }
        });
        jPanel2.add(ctkperhari, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 50, -1, -1));
        jPanel2.add(tanggal2, new org.netbeans.lib.awtextra.AbsoluteConstraints(146, 151, 145, -1));

        ctkperbulan.setBackground(new java.awt.Color(102, 102, 102));
        ctkperbulan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/Printer-icon.png"))); // NOI18N
        ctkperbulan.setText("Cerak Perbulan");
        ctkperbulan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ctkperbulanActionPerformed(evt);
            }
        });
        jPanel2.add(ctkperbulan, new org.netbeans.lib.awtextra.AbsoluteConstraints(297, 170, 139, 27));

        ctkpertahun.setBackground(new java.awt.Color(102, 102, 102));
        ctkpertahun.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/Printer-icon.png"))); // NOI18N
        ctkpertahun.setText("Cetak Petahun");
        ctkpertahun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ctkpertahunActionPerformed(evt);
            }
        });
        jPanel2.add(ctkpertahun, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 110, 140, 30));

        jLabel1.setText("Tanggal");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, 51, -1));

        jLabel2.setText("Dari Tanggal");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(69, 151, 71, 22));

        jLabel3.setText("Sampai Tanggal");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 188, -1, -1));

        jLabel4.setText("Tahun");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 110, -1, 31));
        jPanel2.add(filler1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 103, -1, -1));
        jPanel2.add(filler2, new org.netbeans.lib.awtextra.AbsoluteConstraints(598, 6, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Cetak Laporan Periode");

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/003-newspaper.png"))); // NOI18N

        jLabel20.setBackground(new java.awt.Color(0, 0, 0));
        jLabel20.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel20.setText("AVARTUBOOK");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addGap(213, 213, 213)
                .addComponent(jLabel20)
                .addGap(524, 524, 524))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(138, 138, 138)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel20)
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(34, 34, 34)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 994, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ctkperbulanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ctkperbulanActionPerformed
        // TODO add your handling code here:
            JasperReport jr;
    JasperPrint jp;
    JasperDesign jd;
    try {
        //Map <String, Object> parameter = new HashMap <String, Object>();
        java.sql.Connection conn = (Connection) Koneksi.configDB();
        HashMap parameter = new HashMap();
        parameter.put("bulan", tanggal2.getDate());
        parameter.put("tahun", tanggal3.getDate());
        //sesuaikan folder dan nama ireportnya
        File report = new File("src/Laporan/penjualanperbulan.jrxml");
        jd = JRXmlLoader.load(report);
        jr = JasperCompileManager.compileReport(jd);
        jp = JasperFillManager.fillReport(jr, parameter, conn);
        JasperViewer.viewReport(jp, false);
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, e.getMessage());
    }
    }//GEN-LAST:event_ctkperbulanActionPerformed

    private void ctkperhariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ctkperhariActionPerformed
        // TODO add your handling code here:
    JasperReport jr;
    JasperPrint jp;
    JasperDesign jd;
    try {
        //Map <String, Object> parameter = new HashMap <String, Object>();
        java.sql.Connection conn = (Connection) Koneksi.configDB();
        HashMap parameter = new HashMap();
        parameter.put("hari", tglhari.getDate());
        //sesuaikan folder dan nama ireportnya
        File report = new File("src/Laporan/penjualanharian.jrxml");
        jd = JRXmlLoader.load(report);
        jr = JasperCompileManager.compileReport(jd);
        jp = JasperFillManager.fillReport(jr, parameter, conn);
        JasperViewer.viewReport(jp, false);
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, e.getMessage());
    }
    }//GEN-LAST:event_ctkperhariActionPerformed

    private void ctkpertahunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ctkpertahunActionPerformed
        // TODO add your handling code here:
    JasperReport jr;
    JasperPrint jp;
    JasperDesign jd;
    try {
        //Map <String, Object> parameter = new HashMap <String, Object>();
        java.sql.Connection conn = (Connection) Koneksi.configDB();
        HashMap parameter = new HashMap();
        parameter.put("tahun", tgltahun.getDate());
        //sesuaikan folder dan nama ireportnya
        File report = new File("src/Laporan/penjualanpertahun.jrxml");
        jd = JRXmlLoader.load(report);
        jr = JasperCompileManager.compileReport(jd);
        jp = JasperFillManager.fillReport(jr, parameter, conn);
        JasperViewer.viewReport(jp, false);
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, e.getMessage());
    }
    }//GEN-LAST:event_ctkpertahunActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FORM_cetakPERPRIODE().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ctkperbulan;
    private javax.swing.JButton ctkperhari;
    private javax.swing.JButton ctkpertahun;
    private javax.swing.Box.Filler filler1;
    private javax.swing.Box.Filler filler2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private com.toedter.calendar.JDateChooser tanggal2;
    private com.toedter.calendar.JDateChooser tanggal3;
    private com.toedter.calendar.JDateChooser tglhari;
    private com.toedter.calendar.JDateChooser tgltahun;
    // End of variables declaration//GEN-END:variables
}
